name: TP1 - CI of Sonar by team Delta
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Grant execute permission for Gradle
        run: chmod +x gradlew

      - name: Build and run unit tests
        run: gradle build

      - name: Set up Docker to launch sonar image
        uses: docker/setup-buildx-action@v2

      - name: Build and run SonarQube with Docker
        run: |
          docker pull sonarqube
          docker run -d -p 9000:9000 --name sonarqube sonarqube

      - name: Wait for Sonarqube to start
        run: sleep 30

      - name: Check if Sonarqube is running on docker
        run: |
          docker ps -q --filter "name=sonarqube"
          docker logs sonarqube

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: analyze with sonar cloud
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew build sonar --info
